### PR TITLE
Project: Pagzy

### PR DESCRIPTION
**Pull request by Ankit628792**
# Hackathon Submission: <PROJECT_NAME>

## Name of Team Lead
Ankit Kumar

## GitHub handles of Team Members  
_Enter the GitHub handles of all your team members (including yourself) as separate bullet points_

- @Ankit628792

### Are all of your team members registered on our [Hackathon Signup page](https://apwr.dev/htf24-hackathon)?
_This is a mandatory step for all participants to be considered eligible for judging_

- [x] Yes
- [ ] No

---

## Rules and Code of Conduct  
By submitting this PR, you agree to follow our Rules and Code of Conduct.

- [x] Yes

---

## Anything Else?  
_Any other feedback, queries or information you would like to share with us?_

### CODE REVIEW

**Comment by adityaoberai** [comment]
@Himanshuch8055 a couple of things with your submission:
- It is mandatory to use Appwrite Cloud for the hackathon. Without that, the submission will be deemed invalid.
- Please remove any edits made to the `template_submission.md` file.

**Comment by Ankit628792** [comment]
Project: Pagzy
Integrated Appwrite and using auth service

**Review by Himanshuch8055 — COMMENTED** [review]
Perfect

**Comment by adityaoberai** [comment]
@Ankit628792 as per the submission details, this project does not use any Appwrite Cloud services, which is mandatory for the project to be eligible. For that reason, I will be closing this PR. If you build a project that uses Appwrite before the end of the month, we will be willing to accept the same.

**Pull request closed without merging**
