### PR TITLE
Create WeatherMate.md

### PR DESCRIPTION
**Pull request by rajchaudhary99**
Implemented a location-based weather feature to provide real-time weather updates based on the user’s current geolocation. 
- Integrated "Current Location" functionality, enabling instant access to local weather data. 
- Enhanced the city search feature for instant weather updates by city.
- Added theme persistence using local storage, allowing users to toggle between light and dark modes, with their choice saved for future sessions.
- Updated UI components to support light/dark themes and ensure a seamless experience across devices.
- Resolved responsiveness issues on various screen sizes to improve user interaction and design consistency.

# Hackathon Submission: Weather Mate

## Name of Team Lead
_Enter your full name_

## GitHub handles of Team Members  
_Enter the GitHub handles of all your team members (including yourself) as separate bullet points_

### Are all of your team members registered on our [Hackathon Signup page](https://apwr.dev/htf24-hackathon)?
_This is a mandatory step for all participants to be considered eligible for judging_

- [x] Yes
- [ ] No

---

## Rules and Code of Conduct  
By submitting this PR, you agree to follow our Rules and Code of Conduct.

- [x] Yes

---

## Anything Else?  
_Any other feedback, queries or information you would like to share with us?_

### CODE REVIEW

**Comment by adityaoberai** [comment]
@rajchaudhary99 the project is ineligible for submission because it demonstrates no usage of any Appwrite products, which is mandatory for the hackathon.

**Comment by rajchaudhary99** [comment]
@adityaoberai how?

**Comment by adityaoberai** [comment]
> @adityaoberai how?

@rajchaudhary99 your submitted repo does not show any demonstrable usage of Appwrite. Would you be able to point out to me if that isn't the case?

**Comment by rajchaudhary99** [comment]
@adityaoberai Thank you for your feedback on my submission. I appreciate your input on making the Appwrite integration clearer. Could you please provide guidance on what you’re looking for in terms of “demonstrable usage” of Appwrite? Specifically, I’d like to understand how to better highlight its functionality in my project.

Thanks in advance for your guidance!

**Comment by adityaoberai** [comment]
> @adityaoberai Thank you for your feedback on my submission. I appreciate your input on making the Appwrite integration clearer. Could you please provide guidance on what you’re looking for in terms of “demonstrable usage” of Appwrite? Specifically, I’d like to understand how to better highlight its functionality in my project.
> 
> Thanks in advance for your guidance!

As per the rules, you must implement at least one service available on Appwrite Cloud in your project. Right now, the project does not use any. You should explore Appwrite and pick a service you can implement in your project.

**Comment by adityaoberai** [comment]
@rajchaudhary99 in the meantime, however, I'm closing this PR. You can create another one in case you end up implementing Appwrite in your project.

**Comment by rajchaudhary99** [comment]
@adityaoberai Thank you for the feedback. I understand the requirement to implement at least one Appwrite service in my project. I will explore the available services and select one that best fits the needs of my application.

I am particularly interested in integrating the Authentication service for managing user registrations and logins, and potentially the Database service to store user submissions effectively.

Once I have implemented the selected service, I will create a new pull request. Thank you for your understanding!

**Comment by adityaoberai** [comment]
> @adityaoberai Thank you for the feedback. I understand the requirement to implement at least one Appwrite service in my project. I will explore the available services and select one that best fits the needs of my application.
> 
> I am particularly interested in integrating the Authentication service for managing user registrations and logins, and potentially the Database service to store user submissions effectively.
> 
> Once I have implemented the selected service, I will create a new pull request. Thank you for your understanding!

Sounds good!

**Comment by rajchaudhary99** [comment]
@adityaoberai sir I have created another pull request

**Pull request closed without merging**
