### PR TITLE
Weather App

### PR DESCRIPTION
**Pull request by ChiragTankan**
# Hackathon Submission: <PROJECT_NAME>

## Name of Team Lead
_Enter your full name_

## GitHub handles of Team Members  
_Enter the GitHub handles of all your team members (including yourself) as separate bullet points_

### Are all of your team members registered on our [Hackathon Signup page](https://apwr.dev/htf24-hackathon)?
_This is a mandatory step for all participants to be considered eligible for judging_

- [ ] Yes
- [ ] No

---

## Rules and Code of Conduct  
By submitting this PR, you agree to follow our Rules and Code of Conduct.

- [x] Yes

---

## Anything Else?  
_Any other feedback, queries or information you would like to share with us?_

### CODE REVIEW

**Comment by adityaoberai** [comment]
@ChiragTankan I noticed that your new submission also contains the same project that was rejected earlier in #28 

Please create and submit a new project if you would like to be considered eligible for the hackathon prizes

**Comment by ChiragTankan** [comment]
But I have submitted weather app

**Comment by adityaoberai** [comment]
> Can you tell me how to delete my previous project because I have submitted new one but not showing?

@ChiragTankan you can either reset these 2 commits or delete your fork and create a new one

image

**Comment by adityaoberai** [comment]
By the way, I saw [the project](https://github.com/ChiragTankan/Weather-App) in your repo. To have a valid project for this hackathon, it must use Appwrite, which this does not. I'd recommend looking at the Rules first to ensure you know the minimum requirements for an eligible project

**Pull request closed without merging**
