### PR TITLE
Add virtual-Labs submission to the hackathon repo

### PR DESCRIPTION
**Pull request by SURYANSH-RAI**
# Hackathon Submission: Virtual-Labs

## Name of Team Lead
Suryansh Rai

## GitHub handles of Team Members  
_Enter the GitHub handles of all your team members (including yourself) as separate bullet points_

### Are all of your team members registered on our [Hackathon Signup page](https://apwr.dev/htf24-hackathon)?
_This is a mandatory step for all participants to be considered eligible for judging_

- [x] Yes
- [ ] No

---

## Rules and Code of Conduct  
By submitting this PR, you agree to follow our Rules and Code of Conduct.

- [x] Yes

---

## Anything Else?  
_Any other feedback, queries or information you would like to share with us?_

### CODE REVIEW

**Comment by adityaoberai** [comment]
This submission is not eligible because it uses no Appwrite services in the project repo

**Comment by SURYANSH-RAI** [comment]
i used webhook to deploy and the appwrite dashboard is also showing stats

**Comment by SURYANSH-RAI** [comment]
@adityaoberai you can check i am pasting the image of dashboard 
Screenshot_20241101_225510_Chrome

**Comment by adityaoberai** [comment]
@

**Comment by adityaoberai** [comment]
@SURYANSH-RAI can you point in your project repo where this is used? You can share a link of the exact file or line.

**Comment by SURYANSH-RAI** [comment]
Sir have not exposed that in repo but i have used this repo in my azure account to host as a static website then created a webhook using appwrite webhooks feature and azure function (which is acting as an http trigger) so that when ever i change any thing to my repo it changes to my hosted site and changes will be applied to appwrite too since used anonymous opetion for no auth deploy.

**Comment by SURYANSH-RAI** [comment]
Since azure was disabled in appwrite currently so i used this way othherwise i have deployed directly to appwrite. Also appwrite cloud is currently taking a proper well structured webapps and mine is a static website which is not supported directly and if we try we face error in uploading files in storage like we need to upload every single file manually and tar.gz is unresponsive at that point.

**Comment by adityaoberai** [comment]
@SURYANSH-RAI Appwrite Storage is not meant to host websites at all. And unfortunately, even if Appwrite Webhooks were created to track git changes, there is no evidence offered to demonstrate how the Azure Function was being used to deploy the site. There is no mention of any of this in the Tech Stack section of your submission. What changes are made whenever the webhook is triggered are not explained either. And even with all of that, the app itself doesn't use Appwrite. 

Unfortunately, I do not find enough grounds to reverse the rejection of this submission, and I will be closing this PR for that reason.

**Pull request closed without merging**
