### PR TITLE
Rroist (a form builder website with a CLI) - project submission

### PR DESCRIPTION
**Pull request by Dey11**
# Hackathon Submission: Rroist

## Name of Team Lead
_Enter your full name_

Shubham Parmar

## GitHub handles of Team Members  
_Enter the GitHub handles of all your team members (including yourself) as separate bullet points_

- @Dey11 
- @KIWILmao 
- @Krish-Gupta07

### Are all of your team members registered on our [Hackathon Signup page](https://apwr.dev/htf24-hackathon)?
_This is a mandatory step for all participants to be considered eligible for judging_

- [x] Yes
- [ ] No

---

## Rules and Code of Conduct  
By submitting this PR, you agree to follow our Rules and Code of Conduct.

- [x] Yes

---

## Anything Else?  
_Any other feedback, queries or information you would like to share with us?_
We had a blast making this project - hope y'all like it. Thanks for giving us this space to showcase our ideas.

### CODE REVIEW

**Comment by adityaoberai** [comment]
@Dey11 the project is ineligible for submission because it has [commits from before the hackathon](https://github.com/Dey11/Appwrite-hackathon/commits/master/?after=79869657606412444333cae43c46c2434c6fe916+34) with certain work done, which is not allowed as per the rules

image

**Comment by KIWILmao** [comment]
> @Dey11 the project is ineligible for submission because it has [commits from before the hackathon](https://github.com/Dey11/Appwrite-hackathon/commits/master/?after=79869657606412444333cae43c46c2434c6fe916+34) with certain work done, which is not allowed as per the rules
> 
> image

The initial commits in our project repository were from the boilerplate code we used as a starting point, which is a common practice. All of the actual work we've done for this hackathon was completed within the allotted time frame and does not violate any rules. Here is the boilerplate code repository link https://github.com/Dey11/Nextjs-template so you can verify that the early commits were not our own pre-hackathon work. 
Thank you

**Comment by adityaoberai** [comment]
@KIWILmao alright. I will reopen the PR to review the same. Thank you for informing me.

**Comment by adityaoberai** [comment]
> @KIWILmao alright. I will reopen the PR to review the same. Thank you for informing me.

Having looked at how limited the scope of the boilerplate is, I will allow the submission for now. However, considering that it was still worked on before the hackathon began and that a project team member is also the creator of the boilerplate, the judges will investigate the impact of the boilerplate on the project and score accordingly.

**Pull request merged**
