### PR TITLE
Create Auth_with_Appwrite.md

### PR DESCRIPTION
**Pull request by rajchaudhary99**
A React-based secure authentication system utilizing Appwrite for user registration, login, password recovery, and session management, ensuring scalable and reliable user access control.

# Hackathon Submission: Auth Using Appwite

## Name of Team Lead
Raj Vardhan Chaudhary

## GitHub handles of Team Members  
_Enter the GitHub handles of all your team members (including yourself) as separate bullet points_

### Are all of your team members registered on our [Hackathon Signup page](https://apwr.dev/htf24-hackathon)?
_This is a mandatory step for all participants to be considered eligible for judging_

- [x] Yes
- [ ] No

---

## Rules and Code of Conduct  
By submitting this PR, you agree to follow our Rules and Code of Conduct.

- [x] Yes

---

## Anything Else?  
_Any other feedback, queries or information you would like to share with us?_

### CODE REVIEW

**Review by adityaoberai — APPROVED** [review]

**Comment by rajchaudhary99** [comment]
@adityaoberai  how i collect my gift?

**Comment by adityaoberai** [comment]
> @adityaoberai how i collect my gift?

Sorry, what gift?

**Comment by rajchaudhary99** [comment]
@adityaoberai as mention there are some gift for submitting a project

**Comment by adityaoberai** [comment]
> @adityaoberai as mention there are some gift for submitting a project

Appwrite is providing prizes to top 3 projects after judging.

Since this hackathon occurred during Hacktoberfest, any digital prizes they provide will be available to you. That is not something we have control over, though.

**Comment by rajchaudhary99** [comment]
@adityaoberai  can you provide me any digital certificate for shere on other social media?

**Comment by adityaoberai** [comment]
> @adityaoberai  can you provide me any digital certificate for shere on other social media?
> 

That is not something we provide. Your merged PR is proof of submission.

**Comment by rajchaudhary99** [comment]
@adityaoberai thankyou and happy diwali 🎇

**Pull request merged**
